version: '3'
services:
  web:
    build: .
    command: python main.py
    ports:
      - "5000:5000"
    volumes:
      - .:/website
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - db
  db:
    image: sqlite:latest
    volumes:
      - db_data:/db
volumes:
  db_data: